CREATE TABLE dbo.pricelists (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    CreationDate DATE NOT NULL
);
GO

CREATE TABLE dbo.columns (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(50) NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    PriceListId INT NOT NULL,
    FOREIGN KEY (PriceListId) REFERENCES PriceLists(Id) ON DELETE CASCADE
);
GO

CREATE TABLE dbo.rows (
    Id INT PRIMARY KEY IDENTITY,
    PriceListId INT NOT NULL,
    FOREIGN KEY (PriceListId) REFERENCES PriceLists(Id) ON DELETE CASCADE
);
GO

CREATE TABLE dbo.cells (
    Id INT PRIMARY KEY IDENTITY,
    Value NVARCHAR(MAX) NOT NULL,
    RowId INT NOT NULL,
    ColumnId INT NOT NULL,
    FOREIGN KEY (RowId) REFERENCES Rows(Id) ON DELETE CASCADE,
    FOREIGN KEY (ColumnId) REFERENCES Columns(Id)
);